# Generated by Django 5.2.1 on 2025-05-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='admin_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Comments'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='purpose_of_travel',
            field=models.TextField(default='Not specified', verbose_name='Purpose of Travel'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='travel_end_date',
            field=models.DateField(default='2025-01-01', verbose_name='Travel End Date'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='travel_start_date',
            field=models.DateField(default='2025-01-01', verbose_name='Travel Start Date'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='visa_type',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('work', 'Work'), ('study', 'Study'), ('business', 'Business')], default='tourist', max_length=20, verbose_name='Visa Type'),
        ),
    ]
