# Generated by Django 5.2.1 on 2025-05-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visafee'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='country_flags/', verbose_name='Flag/Image'),
        ),
    ]
