# Generated by Django 5.2.1 on 2025-06-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersubscription_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
