# Generated by Django 5.2.1 on 2025-06-03 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250602_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'В ожидании одобрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('expired', 'Истекла'), ('cancelled', 'Отменена')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subscription'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
